### ISSUE TITLE
No playwright in docker image

### ISSUE THREAD

**Issue by woutervanwijk** [browserless/chrome#1072]
**Describe the bug**
Playwright not available in Docker image

**To Reproduce**
Create a docker-compose file with: 
version: '3.5'

```
services:
  browserservice:
    image: browserless/chrome
    shm_size: 2g
    restart: always
    environment:
      - MAX_CONCURRENT_SESSIONS=2
      - CONNECTION_TIMEOUT=30000
      - MAX_QUEUE_LENGTH=5
      - PREBOOT_CHROME=true
      - ENABLE_DEBUGGER=false
      - KEEP_ALIVE=true
      - DEFAULT_BLOCK_ADS=true
```
When starting the image, browserless comes up with the message args:

playwright: false

even while all other settings seem ok

**Expected behavior**
Playwright:true
