### ISSUE TITLE
Docker Image Default Launch Args and Token

### ISSUE THREAD

**Issue by hatemjaber** [browserless/chrome#1957]
Default launch args and token environment variables not applied when using the docker image. 

```
version: "3.8"

services:
  browserless:
    image: browserless/chrome
    container_name: browserless
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=5
      - CONNECTION_TIMEOUT=35000
      - MAX_QUEUE_LENGTH=5
      - TOKEN=myToken
      - ENABLE_CORS=true
      - ENABLE_XVBF=true
      - EXIT_ON_HEALTH_FAILURE=true
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_TIME=3600000
      - DEFAULT_BLOCK_ADS=true
      - DEFAULT_LAUNCH_ARGS=["--window-size=1920,1080","--proxy-server=http://localhost:8888"]
      - DEFAULT_IGNORE_HTTPS_ERRORS=true
      - DEFAULT_IGNORE_DEFAULT_ARGS=false
      - DISABLED_FEATURES=["downloadEndpoint","functionEndpoint","pdfEndpoint","screencastEndpoint","scrapeEndpoint","statsEndpoint","workspaces"]
      - FUNCTION_ENABLE_INCOGNITO_MODE=true 
```
Proxy server is not used and token is not being respected when using the docker image trying to access the `/content` api endpoint. Regarding the token, whether I pass it in the url or not it will ignore the token. I ran the code directly on my system outside of docker and it works fine as expected. From the docker container it's a different story, the token is not respected and the proxy-server is not being used. I entered the docker container and did the following:

```
export http_proxy=http://proxy:port
curl http://httpbin.org/ip
```
It does see the proxy and works as expected from there.
