### ISSUE TITLE
Error starting sessions with --user-data-dir flag

### ISSUE THREAD

**Issue by arthur-er** [browserless/chrome#2059]
**Describe the bug**
Error starting sessions with --user-data-dir flag
Recording failed stat, cleaning up: "Chrome user data dir not found at '~/session-1'"

**To Reproduce**
1. Run a browserless/chrome:latest container with CONNECTION_TIMEOUT=-1
2. Try to start a session with --user-data-dir
3. See error

**Expected behavior**
Session starts with defined user data dir

**Comment by joelgriffith** [comment]
From what I recall, user-data-dir has to be the full-qualified path, so `~/session-1` should ideally be something like `/Users/arthur/session-1`

**Comment by arthur-er** [comment]
Tried running with a full path (`/tmp/session-1`) but it also not worked, and i can confirm it has access to `/tmp` as sessions started without the flag get a data dir like `/tmp/browserless-data-dir-HPISfU` and works fine

**Comment by joelgriffith** [comment]
Interesting. Is this on latest? Mind sharing your docker run command as well?

**Comment by arthur-er** [comment]
Using a compose file:
```yml
version: '3.8'
services:
  browserless:
    image: browserless/chrome:latest
    ports:
      - 4000:3000
    environment:
      - CONNECTION_TIMEOUT=-1
```
