### ISSUE TITLE
I get a 504 error when I am connecting to browserWSEndpoint via docker-compose

### ISSUE THREAD

**Issue by Zoidberg315** [browserless/chrome#2077]
I have created a container inside my app

```
  browserless:
    image: browserless/chrome:latest
    container_name: 'browserless'
    ports:
      - "3000:3000"
    networks:
      - test-network

#Docker Networks
networks:
  test-network:
    driver: bridge
```

then I try to connect and keep getting:
```
    const browser = await puppeteer.connect({
      browserWSEndpoint: `ws://browserless:3000/`,
      defaultViewport: null, // <= set this to have viewport emulation off
    });
    const page = await browser.newPage();
    await page.evaluateOnNewDocument(setWindowDimensions, viewport);
    await page.setViewport(viewport);
    await page.emulateMediaType('screen');

    await page.goto(url, { waitUntil: 'networkidle0' });
    await page.waitForTimeout(10000);
    // await page.waitForSelector(waitFor);

    await page.pdf({
      path: pdfPath,
      printBackground: true,
      height: viewport.height,
      width: viewport.width,
    });

    await browser.close();
  } catch (error) 
```

what am I doing wrong ? 
I also tried not from docker to connect to browserWSEndpoint: `ws://localhost:3000/` but I get a 504 error
Although the page http://localhost:3000 is available and working properly
