### ISSUE TITLE
Unable to  /pdf times out

### ISSUE THREAD

**Issue by gufoe** [browserless/chrome#2110]
I am unable to increase the timeout of the /pdf endpoint and keep getting a 400 after 30 seconds.
This is documented and I believe I am just getting this wrong.
I thus get the error `waiting for Page.printToPDF failed: timeout 30000ms exceeded`.

What I tried:  
- updating the CONNECTION_TIMEOUT env variable to anything (60000, -1, 0): nothing changes.
- calling the endpoint with a timeout /pdf?timeout=60000
- passing the timeout parameter to the `gotoOptions` parameter (I am using `waitUntil: networkidle0`) 

The following is my `docker-compose.yml`
```yaml
version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    environment:
      - MAX_CONCURRENT_SESSIONS=4
      - CONNECTION_TIMEOUT=-1
      - MAX_QUEUE_LENGTH=4
      - PREBOOT_CHROME=false
      - DEMO_MODE=false
      - ENABLE_DEBUGGER=false
```
