### ISSUE TITLE
IgnoreHTTPSErrors only sometimes works?

### ISSUE THREAD

**Issue by byt3bl33d3r** [browserless/chrome#2485]
**Describe the bug**

It looks like sometimes browserless doesn't launch chrome with the `ignoreHTTPSErrors` flag even though it's specified in the `docker-compose.yml` file and/or using the URL parameter.

**To Reproduce**

In my `docker-compose.yml`:
```yaml
  chrome:
    image: browserless/chrome:latest
    security_opt:
      - "seccomp=../chromium.json"
    deploy:
      replicas: 2
    expose:
      - 3000
    environment:
     # https://docs.browserless.io/docs/docker.html
     - DEFAULT_IGNORE_HTTPS_ERRORS=true
     - ENABLE_DEBUGGER=false
     - DEFAULT_IGNORE_DEFAULT_ARGS=["--no-sandbox"]
     - DEFAULT_STEALTH=true
     - FUNCTION_ENABLE_INCOGNITO_MODE=true
     - KEEP_ALIVE=true
     - PREBOOT_CHROME=true
     - EXIT_ON_HEALTH_FAILURE=true
```

Python script using playwright:

```python
import asyncio
import logging
from urllib.parse import urlparse
from playwright.async_api import async_playwright
from playwright._impl._api_types import Error as PlaywrightError

URLS = [
    'https://bot.sannysoft.com/',
    'https://arh.antoinevastel.com/bots/areyouheadless',
    'https://200.70.58.134:8443/',
    'https://200.55.247.6:3000/',
    'https://190.227.183.117:8443/',
    'https://190.221.139.82:8443/',
    'https://181.30.162.226:4433/'
]

queue = asyncio.Queue()

log = logging.getLogger('play')
log.addHandler(logging.StreamHandler())
log.setLevel(logging.DEBUG)

async def screenshot(url):
    async with async_playwright() as p:
        browser = await p.chromium.connect_over_cdp('ws://chrome:3000/?ignoreHTTPSErrors=true&ignoreDefaultArgs=--no-sandbox')
        try:
            log.debug(url)
            parsed_url = urlparse(url) 
            page = await browser.new_page()

            try:
                await page.goto(url, wait_until="networkidle")
            except PlaywrightError as e:
                if not 'CERT' in str(e):
                    raise

                log.debug('Caught certificate error')
                await page.goto(url, wait_until="networkidle")

            await page.screenshot(path=f'./play/screenshot_{parsed_url.scheme}_{parsed_url.netloc}_{parsed_url.port}.png', full_page=True)
        finally:
            await browser.close()

async def producer():
    for url in URLS:
        queue.put_nowait(url)

async def consumer():
    url = await queue.get()
    try:
        await screenshot(url)
    except Exception as e:
        log.error(f'{e}')
    finally:
        queue.task_done()

async def main():
    n_threads = 8
    asyncio.create_task(producer())

    while queue.qsize() == 0:
        await asyncio.sleep(0.1)

    while queue.qsize() > 0:
        tasks = [
            consumer()
            for _ in range(
                n_threads if queue.qsize() > n_threads else queue.qsize()
            )
        ]
        await asyncio.gather(*tasks)

asyncio.run(main())
```

**Expected behavior**
Browserless should be instructing chrome to ignore HTTPS certificate errors if `DEFAULT_IGNORE_HTTPS_ERRORS=true` is specified through docker or via the connection URL .

**Screenshots**
First run of the Python script everything is fine:
<img width="618" alt="image" src="https://user-images.githubusercontent.com/5151193/175359718-aff759eb-264c-4802-bf12-84b0cd26ad89.png">

Third time running the script, certificate error is thrown when calling `page.goto()`:
<img width="569" alt="image" src="https://user-images.githubusercontent.com/5151193/175360076-c94b0c20-939a-41ae-b2f8-704852a1ba76.png">

**Additional context**

Currently working around this by catching any error with `CERT` in the string and calling `page.goto()` again (line 35-40 in the python script, no clue why this works). Obviously this isn't ideal, chrome should be ignoring cert errors everytime it gets started if the correct knobs are turned.
