### ISSUE TITLE
Debug logs are created even with ENABLE_DEBUGGER=false

### ISSUE THREAD

**Issue by mrahmadt** [browserless/chrome#2621]
**Describe the bug**
As per the document https://docs.browserless.io/docs/docker.html#disabling-the-debugger, you can disable the debug mode by using "ENABLE_DEBUGGER=false", I'm using the below docker-compose and still see debug messages

```
version: '3'

services:
  browserless:
    image: browserless/chrome:latest
    container_name: browserless
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - /dev/shm:/dev/shm
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "2"
    environment:
     - ENABLE_DEBUGGER=false
     - DEFAULT_IGNORE_HTTPS_ERRORS=true
     - DEFAULT_STEALTH=true
     - FUNCTION_ENABLE_INCOGNITO_MODE=true
     - KEEP_ALIVE=false
     - PREBOOT_CHROME=true
     - DEFAULT_BLOCK_ADS=true
     - ENABLE_API_GET=true
     - HOST=0.0.0.0
     - MAX_CONCURRENT_SESSIONS=5
     - DEFAULT_LAUNCH_ARGS=["--disable-translate","--disable-extensions","--disable-remote-fonts","--disable-renderer-accessibility","--disable-notifications","--disable-plugins","--disable-sync","--disable-default-apps","--start-maximized","--no-sandbox"]
     - CONNECTION_TIMEOUT=-1
     - EXIT_ON_HEALTH_FAILURE=true
     - TOKEN=xxxx
     - MAX_QUEUE_LENGTH=10

```

**Expected behavior**
Not to generate debug logs

```
# docker logs browserless

[1660847213.886][DEBUG]: DevTools WebSocket Event: Runtime.executionContextCreated (session_id=A5AEC1B9EE8AD3D519CC6EF3B34F5ED0) A5202ED94705B6DA58F1839ACCA774BD {
   "context": {
      "auxData": {
         "frameId": "4618B9321B7A84505AFDE88193482C96",
         "isDefault": false,
         "type": "isolated"
      },
      "id": 20,
      "name": "__puppeteer_utility_world__",
      "origin": "",
      "uniqueId": "5390011193807668097.7675343012048991706"
   }
}
[1660847213.886][DEBUG]: DevTools WebSocket Event: Page.frameStoppedLoading (session_id=A5AEC1B9EE8AD3D519CC6EF3B34F5ED0) A5202ED94705B6DA58F1839ACCA774BD {
   "frameId": "4618B9321B7A84505AFDE88193482C96"
}
[1660847213.886][DEBUG]: DevTools WebSocket Command: Runtime.evaluate (id=95) (session_id=A5AEC1B9EE8AD3D519CC6EF3B34F5ED0) A5202ED94705B6DA58F1839ACCA774BD {
   "expression": "1"
}
[1660847213.888][DEBUG]: DevTools WebSocket Response: Runtime.evaluate (id=95) (session_id=A5AEC1B9EE8AD3D519CC6EF3B34F5ED0) A5202ED94705B6DA58F1839ACCA774BD {
   "result": {
      "description": "1",
      "type": "number",
      "value": 1
   }
}

```

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Browser Chrome
