### ISSUE TITLE
Doesn't run, assertion failed

### ISSUE THREAD

**Issue by AndreKR** [browserless/chrome#2862]
**Describe the bug**
It doesn't start at all.

**To Reproduce**
This looks like a crash to me:

```
$ docker run -it --rm browserless/chrome:latest
node[8]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
 1: 0xb06730 node::Abort() [node]
 2: 0xb067ae  [node]
 3: 0xb756fe  [node]
 4: 0xb757c6 node::NodePlatform::NodePlatform(int, v8::TracingController*) [node]
 5: 0xacc654 node::InitializeOncePerProcess(int, char**, node::InitializationSettingsFlags, node::ProcessFlags::Flags) [node]
 6: 0xacd239 node::Start(int, char**) [node]
 7: 0x7fd633dafd90  [/lib/x86_64-linux-gnu/libc.so.6]
 8: 0x7fd633dafe40 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
 9: 0xa4080c  [node]
```
**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.8.2003 (Core)

**Comment by CircuitGuy** [comment]
Duplicate issue on a fresh pull (first time trying). Pulled from latest with the changedetection.io defaults.

Error is basically identical.
```
node[10]: ../src/node_platform.cc:61:std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start(): Assertion `(0) == (uv_thread_create(t.get(), start_thread, this))' failed.
...
```

docker-compose.yml snippet
```
    playwright-chrome:
        hostname: playwright-chrome
        image: browserless/chrome
        restart: unless-stopped
        environment:
            - SCREEN_WIDTH=1920
            - SCREEN_HEIGHT=1024
            - SCREEN_DEPTH=16
            - ENABLE_DEBUGGER=false
            - PREBOOT_CHROME=true
            - CONNECTION_TIMEOUT=300000
            - MAX_CONCURRENT_SESSIONS=10
            - CHROME_REFRESH_TIME=600000
            - DEFAULT_BLOCK_ADS=true
            - DEFAULT_STEALTH=true
```

Kernel: 5.4.78-2-pve
Docker: 18.09.1, build 4c52b90
