### ISSUE TITLE
Chrome sessions are not loaded in debugger

### ISSUE THREAD

**Issue by hotrush** [browserless/chrome#4410]
Current session list is empty at http://localhost:3000/debugger/?token=secret
Devtool says that /chromesessions endpoint returns 404

<img width="1223" alt="image" src="https://github.com/user-attachments/assets/77ec06b9-387f-4fb1-a8e7-c03d08542a35">

Using ghcr.io/browserless/chrome:v2.23.0

**Comment by joelgriffith** [comment]
Looks like there's calls to sessions that 404 in your network tab -- are you running this image behind a proxy?

**Comment by hotrush** [comment]
@joelgriffith no any proxies, just a docker compose locally

**Comment by joelgriffith** [comment]
Thanks for that: can you share you docker-compose file with me?

**Comment by hotrush** [comment]
@joelgriffith hey, sorry, missed your message

```
version: "3"

services:
  ...

  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.browserless
    ports:
      - 3000:3000
    environment:
      - KEEP_ALIVE=false
      - ENABLE_DEBUGGER=true
      - CONCURRENT=10
      - TIMEOUT=1800000
      - EXIT_ON_HEALTH_FAILURE=false
      - ENABLE_XVBF=false
      - TOKEN=secret
```

and dockerfile

```
FROM ghcr.io/browserless/chrome:v2.23.0

RUN npm install puppeteer-extra-plugin-recaptcha

ENV FUNCTION_EXTERNALS '["puppeteer-extra-plugin-recaptcha", "puppeteer-extra"]'
```
