### ISSUE TITLE
Bug with trackingId parameter

### ISSUE THREAD

**Issue by STK913** [browserless/chrome#657]
Hello, I noticed a strange problem with the trackingId parameter. This is ignored if no other parameter with 2 dashes is present in the URL.

The following example ignores the trackingId:
```
puppeteer.connect({
	browserWSEndpoint: "ws://domain.com:port?token=xxx&keepalive=30000&trackingId=1234"
});
```

But the one accepts it (with --test):
```
puppeteer.connect({
	browserWSEndpoint: "ws://domain.com:port?token=xxx&keepalive=30000&trackingId=1234&--test="
});
```

I performed my tests with the latest version of the docker available: browserless/chrome:1.29-chrome-stable
And to check if the trackingId exists, I use the following URL: http://domain.com:port/sessions

Do not hesitate if you have any questions.

**Comment by joelgriffith** [comment]
Sadly I cannot reproduce this:

```sh
# Started the container
docker run -p 3000:3000 --rm --name browserless browserless/chrome:1.29-chrome-stable
```

```js
// Generate some files
const puppeteer = require('puppeteer');

async function run() {
  const browser = await puppeteer.connect({
  browserWSEndpoint: 'ws://localhost:3000?trackingId=123'
  });

  const page = await browser.newPage();

  // Here we generate a CSV file and have the browser download it
  await page.evaluate(() => {
    const rows = [
      ["name1", "city1", "some other info"],
      ["name2", "city2", "more info"]
    ];
    let csvContent = "data:text/csv;charset=utf-8,";
    rows.forEach(function(rowArray){
      let row = rowArray.join(",");
      csvContent += row + "\r\n";
    }); 
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", "data.csv");
    document.body.appendChild(link);

    return link.click();
  });

  browser.close();
}

run();
```

Test to see if the files are there:

```sh
$ docker exec -it -u root browserless bash
$ root@3e96cf117def: cd /usr/src/app/workspace/123
$ root@3e96cf117def:/usr/src/app/workspace/123# stat data.csv 
  File: data.csv
  Size: 52              Blocks: 8          IO Block: 4096   regular file
Device: 70h/112d        Inode: 3548674     Links: 1
Access: (0644/-rw-r--r--)  Uid: (  999/blessuser)   Gid: (  999/blessuser)
Access: 2020-03-31 01:44:46.238508000 +0000
Modify: 2020-03-31 01:44:46.238508000 +0000
Change: 2020-03-31 01:44:46.241508000 +0000
 Birth: -
```

Is there more to your docker container's environment variables?

**Comment by STK913** [comment]
Hello,

Here is the docker-compose which contains the environment variables:

```
version: '2'
services:
  browserless:
    image: browserless/chrome:1.29-chrome-stable
    environment:
      CONNECTION_TIMEOUT: '-1'
      EXIT_ON_HEALTH_FAILURE: 'true'
      MAX_CONCURRENT_SESSIONS: '100'
      MAX_QUEUE_LENGTH: '2147483647'
      METRICS_JSON_PATH: /root/metrics.json
      PREBOOT_CHROME: 'true'
      TOKEN: xxx
    volumes:
    - /docker/browserless/metrics.json:/root/metrics.json
    ports:
    - xxx:3000/tcp
```

My test code:
```
import * as puppeteer from 'puppeteer'; // puppeteer@2.1.1
let browser: Browser = await puppeteer.connect({browserWSEndpoint: "ws://domain:port?token=xxx&keepalive=30000&trackingId=12345&--test="});
let page: Page = await browser.newPage();
await page.goto("https://google.com");
```

The result on /sessions with --test= :
`{"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=0.0.0.0:3000/devtools/page/xxx","id":"xxx","title":"Google","type":"page","url":"https://www.google.com/","webSocketDebuggerUrl":"ws://0.0.0.0:3000/devtools/page/xxx","browserId":"xxx","browserWSEndpoint":"ws://0.0.0.0:3000/devtools/browser/xxx","port":"51407","trackingId":"1234"}`

Without --test= :
`{"description":"","devtoolsFrontendUrl":"/devtools/inspector.html?ws=0.0.0.0:3000/devtools/page/xxx","id":"xxx","title":"Google","type":"page","url":"https://www.google.com/","webSocketDebuggerUrl":"ws://0.0.0.0:3000/devtools/page/xxx","browserId":"xxx","browserWSEndpoint":"ws://0.0.0.0:3000/devtools/browser/xxx","port":"45409","trackingId":null}`
