### ISSUE TITLE
Prometheus metrics endpoint does not work

### ISSUE THREAD

**Issue by alikhil** [browserless/chrome#680]
**Describe the bug**
Prometheus metrics endpoint does not work.

**To Reproduce**
1. Create docker-compose.yml:
```yaml
version: '3'

services:

  browserless:
    image: browserless/chrome:1.31.1-puppeteer-2.1.1
    ports:
      - "80:3000"
    restart: always
    environment:
      MAX_QUEUE_LENGTH: 0
      PREBOOT_CHROME: 'true'
      TOKEN: mytoken
      ENABLE_DEBUGGER: 'false'
      CONNECTION_TIMEOUT: 300000
      EXIT_ON_HEALTH_FAILURE: 'true'
      MAX_CONCURRENT_SESSIONS: 14
      WORKSPACE_DELETE_EXPIRED: 'true'
      WORKSPACE_EXPIRE_DAYS: 7
```
2. Run docker-compose: `docker-compose up -d`
3. Try to fetch prometheus metrics `curl http://localhost:80/metrics?token=mytoken`
4. Getting:

```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /prometheus</pre>
</body>
</html>
```

**Expected behavior**
I expect to get list of metrics as it is described in https://github.com/browserless/chrome/pull/381
