### ISSUE TITLE
Token Authenticated /Prometheus Handler hands back 403

### ISSUE THREAD

**Issue by arenstar** [browserless/chrome#866]
**Describe the bug**
Kubernetes/Prometheus utilises a servicemonitor which scrapes endpoints using the following syntax

```
      endpoints:
        - interval: 30s
          params:
            token: "blah"
          path: /prometheus
          port: http
          scheme: http
```

However browserless is still handing back a 403 status code with the content with a valid token.

**Expected behavior**
I expect a status code 200 and a happy prometheus
